default:
	go build -o bin/server server.go
	go build -o bin/unary_client unary_client.go
	go build -o bin/unary_per_conn_client unary_per_conn_client.go
	go build -o bin/stream_client stream_client.go
